# Generated by Django 5.2.13 on 2026-06-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('page_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=100)),
                ('description', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('shifting_date', models.DateField()),
                ('client_name', models.CharField(max_length=200)),
                ('bc_pc', models.CharField(choices=[('BC', 'BC'), ('PC', 'PC'), ('Both', 'Both')], max_length=20)),
                ('office_no', models.CharField(max_length=100)),
                ('deal_amount', models.CharField(max_length=100)),
                ('token_amount', models.CharField(max_length=100)),
                ('security_amount', models.CharField(max_length=100)),
                ('deal_by', models.CharField(max_length=100)),
                ('brokerage', models.CharField(max_length=100)),
                ('cabin', models.CharField(max_length=100)),
                ('work_station', models.CharField(max_length=100)),
                ('maintenance', models.CharField(max_length=100)),
                ('nature_of_work', models.CharField(max_length=200)),
                ('gst', models.CharField(choices=[('Included', 'Included'), ('Excluded', 'Excluded'), ('Not Applicable', 'Not Applicable')], max_length=50)),
                ('pending_amount', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bc_pc', models.CharField(choices=[('BC', 'BC'), ('PC', 'PC'), ('Both', 'Both')], max_length=20)),
                ('office_no', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('attend_by', models.CharField(max_length=100)),
                ('brokerage_type', models.CharField(choices=[('Brokerage', 'Brokerage'), ('Direct', 'Direct'), ('Both', 'Both')], max_length=20)),
                ('requirement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('expected_ctc', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='job_resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='group_app.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='group_app.jobcategory'),
        ),
    ]
